<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Services\Zoho\ZohoTokenService;
use App\Services\Zoho\ZohoClient;
use Illuminate\Support\Facades\Log;

class ZohoTestInvoice extends Command
{
    protected $signature = 'zoho:test-invoice';
    protected $description = 'Test the Zoho Invoice integration by creating a test contact and invoice';

    public function handle()
    {
        $this->info('');
        $this->info('╔══════════════════════════════════════════════════════════════╗');
        $this->info('║           ZOHO INVOICE INTEGRATION TEST                     ║');
        $this->info('╚══════════════════════════════════════════════════════════════╝');
        $this->info('');

        try {
            // Step 1: Test token refresh
            $this->info('1️⃣  Testing OAuth Token Refresh...');
            $tokenService = app(ZohoTokenService::class);
            $accessToken = $tokenService->getAccessToken();
            $this->info('   ✅ Access token obtained: ' . substr($accessToken, 0, 20) . '...');

            // Step 2: Test API connection via ZohoClient
            $this->info('');
            $this->info('2️⃣  Testing API Connection (List Contacts)...');
            $client = app(ZohoClient::class);
            $contacts = $client->get('/contacts', ['per_page' => 5]);
            $contactCount = count($contacts['contacts'] ?? []);
            $this->info("   ✅ Contacts API works! Found {$contactCount} contact(s).");

            // Step 3: Create a test contact
            $this->info('');
            $this->info('3️⃣  Creating Test Contact...');
            $testContactData = [
                'contact_name' => 'Test Customer - Elbildad ' . now()->format('His'),
                'email' => 'test_' . now()->timestamp . '@elbildad-test.com',
                'contact_type' => 'customer',
                'billing_address' => [
                    'address' => '123 Test Street',
                    'city' => 'Abuja',
                    'state' => 'FCT',
                    'country' => 'Nigeria',
                ],
            ];

            $contactResponse = $client->post('/contacts', $testContactData);
            $contactId = $contactResponse['contact']['contact_id'] ?? null;
            $contactName = $contactResponse['contact']['contact_name'] ?? 'Unknown';

            if (!$contactId) {
                $this->error('   ❌ Failed to create contact.');
                $this->line('   Response: ' . json_encode($contactResponse, JSON_PRETTY_PRINT));
                return 1;
            }

            $this->info("   ✅ Contact created: {$contactName} (ID: {$contactId})");

            // Step 4: Create a test invoice
            $this->info('');
            $this->info('4️⃣  Creating Test Invoice...');
            $invoiceData = [
                'customer_id' => $contactId,
                'date' => now()->format('Y-m-d'),
                'due_date' => now()->addDays(14)->format('Y-m-d'),
                'notes' => 'This is a test invoice generated by the Zoho integration test.',
                'line_items' => [
                    [
                        'name' => 'Consulting Service',
                        'description' => 'Professional consulting - 2 hours',
                        'rate' => 150.00,
                        'quantity' => 2,
                    ],
                    [
                        'name' => 'Technical Support',
                        'description' => 'Remote technical support - 1 hour',
                        'rate' => 100.00,
                        'quantity' => 1,
                    ],
                ],
            ];

            $invoiceResponse = $client->post('/invoices', $invoiceData);
            $invoiceId = $invoiceResponse['invoice']['invoice_id'] ?? null;
            $invoiceNumber = $invoiceResponse['invoice']['invoice_number'] ?? 'N/A';
            $invoiceTotal = $invoiceResponse['invoice']['total'] ?? 0;
            $invoiceStatus = $invoiceResponse['invoice']['status'] ?? 'unknown';

            if (!$invoiceId) {
                $this->error('   ❌ Failed to create invoice.');
                $this->line('   Response: ' . json_encode($invoiceResponse, JSON_PRETTY_PRINT));
                return 1;
            }

            $this->info("   ✅ Invoice created successfully!");
            $this->info("      Invoice Number: {$invoiceNumber}");
            $this->info("      Invoice ID:     {$invoiceId}");
            $this->info("      Total:          \${$invoiceTotal}");
            $this->info("      Status:         {$invoiceStatus}");

            // Step 5: Retrieve the invoice back
            $this->info('');
            $this->info('5️⃣  Retrieving Invoice Details...');
            $fetchedInvoice = $client->get("/invoices/{$invoiceId}");
            $fetched = $fetchedInvoice['invoice'] ?? [];
            $this->info("   ✅ Invoice retrieved successfully!");
            $this->info("      Customer:  " . ($fetched['customer_name'] ?? 'N/A'));
            $this->info("      Date:      " . ($fetched['date'] ?? 'N/A'));
            $this->info("      Due Date:  " . ($fetched['due_date'] ?? 'N/A'));
            $this->info("      Items:     " . count($fetched['line_items'] ?? []));

            // Step 6: List invoices
            $this->info('');
            $this->info('6️⃣  Listing Recent Invoices...');
            $invoiceList = $client->get('/invoices', ['per_page' => 5, 'sort_column' => 'created_time', 'sort_order' => 'D']);
            $invoices = $invoiceList['invoices'] ?? [];
            $this->info("   ✅ Found " . count($invoices) . " recent invoice(s):");
            foreach ($invoices as $inv) {
                $this->line("      • {$inv['invoice_number']} | {$inv['customer_name']} | \${$inv['total']} | {$inv['status']}");
            }

            // Step 7: Cleanup - Delete the test invoice and contact
            $this->info('');
            $this->info('7️⃣  Cleaning up test data...');

            try {
                $client->delete("/invoices/{$invoiceId}");
                $this->info("   ✅ Test invoice deleted.");
            } catch (\Exception $e) {
                $this->warn("   ⚠️  Could not delete test invoice: " . $e->getMessage());
            }

            try {
                $client->delete("/contacts/{$contactId}");
                $this->info("   ✅ Test contact deleted.");
            } catch (\Exception $e) {
                $this->warn("   ⚠️  Could not delete test contact: " . $e->getMessage());
            }

            // Summary
            $this->info('');
            $this->info('╔══════════════════════════════════════════════════════════════╗');
            $this->info('║              ALL TESTS PASSED! ✅                            ║');
            $this->info('╚══════════════════════════════════════════════════════════════╝');
            $this->info('');
            $this->table(
                ['Test', 'Result'],
                [
                    ['OAuth Token Refresh', '✅ PASS'],
                    ['List Contacts', '✅ PASS'],
                    ['Create Contact', '✅ PASS'],
                    ['Create Invoice', '✅ PASS'],
                    ['Retrieve Invoice', '✅ PASS'],
                    ['List Invoices', '✅ PASS'],
                    ['Cleanup (Delete)', '✅ PASS'],
                ]
            );
            $this->info('');
            $this->info('Your Zoho Invoice integration is fully functional! 🚀');
            $this->info('');

            return 0;

        } catch (\Exception $e) {
            $this->error('');
            $this->error('❌ TEST FAILED: ' . $e->getMessage());
            $this->error('');
            Log::error('Zoho test invoice failed: ' . $e->getMessage(), ['trace' => $e->getTraceAsString()]);

            if (str_contains($e->getMessage(), 'refresh')) {
                $this->warn('Hint: Your refresh token may be invalid. Run `php artisan zoho:setup` again.');
            }

            return 1;
        }
    }
}
